# Generated by Django 3.2 on 2021-04-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('top_wear', 'Top Wear'), ('bottom_wear', 'Bottom Wear')], max_length=20)),
                ('product_img', models.ImageField(upload_to='product_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('dhaka', 'Dhaka'), ('borishal', 'Borishal'), ('jessor', 'Jessor'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('sylet', 'Sylet'), ('rongpur', 'Rongpur')], max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
