# Generated by Django 3.2 on 2021-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Laptop'), ('redme', 'Redme')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
