# Generated by Django 3.2 on 2021-04-20 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210412_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('dhaka', 'Dhaka'), ('borishal', 'Borishal'), ('jessor', 'Jessor'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('sylet', 'Sylet'), ('rongpur', 'Rongpur')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
