# Generated by Django 3.2 on 2021-05-03 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='date_auto_now',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='date_auto_now_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
