# Generated by Django 3.2 on 2021-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210503_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('packed', 'Packed'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('cancel', 'Cancel')], default='Pending', max_length=10),
        ),
    ]
