# Generated by Django 3.2 on 2021-05-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210504_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulytic_labs_test',
            name='payment_method',
            field=models.CharField(choices=[('cash on deliver', 'Cash On Deliver'), ('bkash', 'Bkash'), ('visa', 'Visa Cart')], default='bkash', max_length=20),
        ),
        migrations.AlterField(
            model_name='mulytic_labs_test',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
