# Generated by Django 3.2 on 2021-05-07 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210506_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulytic_labs_test',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mulytic_labs_test',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
