# Generated by Django 3.2 on 2021-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210507_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulytic_labs_test',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/qr_code/'),
        ),
    ]
